site_name: PSYCHEER's Documentations
site_url: https://psycheer.github.io/
site_author: PSYCHEER
theme:
  name: material
  locale: en
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - content.code.copy
    - search.suggest
    - search.highlight
    - search.share
    - navigation.tracking
    - navigation.footer
    - navigation.top
    - navigation.path
    - navigation.expand
    - navigation.sections
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: deep purple
      accent: purple

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: deep purple
      accent: purple

extra_css:
  - css/all.css
markdown_extensions:
  - neoteroi.timeline
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.magiclink
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.details

nav:
  - Home: en/index.md
  - NovaBot:
    - Why to choose NovaBot: en/NovaBot/novaIndex.md
    - Setting up the bot: en/NovaBot/setup.md
    - Addons:
      - Installation: en/NovaBot/addons/addons.md
      - List: en/NovaBot/addons/list.md
      - Creation: en/NovaBot/addons/addonCreation.md

plugins:
  - section-index
  - search:
      lang:
        - en
        - cs
        - es
        - pl
  - social
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: True
          name: English
          copyright: Made with ❤️ by <a href="https://github.com/PSYCHEER">PSYCHEER</a>
          site_name: PSYCHEER's Documentations
          nav:
            - Home: en/index.md
            - NovaBot:
              - Why to choose NovaBot: en/NovaBot/novaIndex.md
              - Setting up the bot: en/NovaBot/setup.md
              - Configuration: en/NovaBot/config.md
              - Addons:
                - Installation: en/NovaBot/addons/addons.md
                - List: en/NovaBot/addons/list.md
                - Creation: en/NovaBot/addons/addonCreation.md
            - Timeline: en/timeline.md
        - locale: es
          name: Español
          site_name: Documentaciones de PSYCHEER
          copyright: Hecho con ❤️ por <a href="https://github.com/PSYCHEER">PSYCHEER</a>
          admonition_translations:
            success: Éxito
            tip: Consejo
            warning: Advertencia
            danger: Peligro
          nav:
            - Inicio: es/index.md
            - NovaBot:
              - Por qué elegir NovaBot: es/NovaBot/novaIndex.md
              - Configuración del bot: es/NovaBot/setup.md
              - Configuración: es/NovaBot/config.md
              - Complementos:
                - Instalación: es/NovaBot/addons/addons.md
                - Listado: es/NovaBot/addons/list.md
                - Creación: es/NovaBot/addons/addonCreation.md
        - locale: pl
          name: Polski
          site_name: Dokumentacje PSYCHEER
          copyright: Wykonane z ❤️ przez <a href="https://github.com/PSYCHEER">PSYCHEER</a>
          admonition_translations:
            success: Sukces
            tip: Wskazówki
            warning: Ostrzeżenie
            danger: Zagrożenie
          nav:
            - Dom: pl/index.md
            - NovaBot:
              - Dlaczego wybrać NovaBot: pl/NovaBot/novaIndex.md
              - Konfiguracja bota: pl/NovaBot/setup.md
              - Konfiguracja: pl/NovaBot/config.md
              - Dodatki:
                - Instalacja: pl/NovaBot/addons/addons.md
                - Wykaz: pl/NovaBot/addons/list.md
                - Tworzenie: pl/NovaBot/addons/addonCreation.md
        - locale: cs
          name: Česky
          site_name: Dokumentace PSYCHEER
          copyright: Vytvořeno s ❤️ od <a href="https://github.com/PSYCHEER">PSYCHEER</a>
          admonition_translations:
            success: Úspěch
            warning: Varování
            danger: Nebezpečí
          nav:
            - Domů: cs/index.md
            - NovaBot:
              - Proč si zvolit NovaBot: cs/NovaBot/novaIndex.md
              - Nastavení bota: cs/NovaBot/setup.md
              - Konfigurace: cs/NovaBot/config.md
              - Přídavky:
                - Instalace: cs/NovaBot/addons/addons.md
                - Seznam: cs/NovaBot/addons/list.md
                - Tvorba: cs/NovaBot/addons/addonCreation.md
  - git-revision-date-localized

extra:
  generator: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/PSYCHEER
    - icon: fontawesome/brands/discord
      link: https://bbb.crafttale.eu

copyright: Made with ❤️ by <a href="https://github.com/PSYCHEER">PSYCHEER</a>